action_mode: dexjoco_joint
batch_size: 64
depth: 12
freeze_steps: 1000
hidden_size: 768
image_size: 384
iters: 200000
learning_rate: 0.0001
num_actions: 10
save_interval: 10000
smolvlm_model_path: HuggingFaceTB/SmolVLM-500M-Instruct
use_adaln: false
warmup_steps: 0
